<a href="https://colab.research.google.com/github/wtnscti/tcc-ifsuldestemg-web/blob/main/analiseexplratoria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Importing necessary tensorflow library and printing the TF version.
import tensorflow as tf

print("TensorFlow version: ",tf.version.VERSION)

TensorFlow version:  2.17.0

In [28]:
# Importing necessary tensorflow library and printing the TF version.
import os
# Here we'll import Pandas and Numpy data processing libraries
import pandas as pd
import numpy as np
from datetime import datetime
# Use matplotlib for visualizing the model
import matplotlib.pyplot as plt
# Use seaborn for data visualization
import seaborn as sns
%matplotlib inline

In [8]:
# Creating directory to store dataset
if not os.path.isdir("../sample_data/transport"):
    os.makedirs("../sample_data/transport")

In [34]:
# Reading "untidy_vehicle_data_toy.csv" file using the read_csv() function included in the pandas library.
#df_transport = pd.read_csv('../sample_data/transport/eletrodom.csv',encoding='latin-1')

# Ler o arquivo Excel
df_transport = pd.read_excel('/sample_data/transport/eletrodom.xlsx')

# Output the first five rows.
df_transport.head()

,AGRUPADOR,STATUS,TÍTULO,CÓDIGO FORNECEDOR / SKU INTERNO,EAN,NBM,ORIGEM,DESCRICAO,DESCRIPTION,CATEGORIA,...,IMAGEM 9,IMAGEM 10,NOME VARIAÇÃO 1,VALOR VARIAÇÃO 1,NOME VARIAÇÃO 2,VALOR VARIAÇÃO 2,NOME VARIAÇÃO 3,VALOR VARIAÇÃO 3,GÊNERO,PERMITIR ANÚNCIOS AUTOMÁTICOS
0,154519990,Ativo,Fogão 4 Bocas Atlas Titanium Automático E Mesa...,MKP000418000118,7897180505332,NaN,0,Fogão 4 Bocas Atlas Titanium Automático E Mesa...,<h2>Fogão 4 Bocas Atlas Mônaco Plus Titanium C...,Eletrodomesticos/Fogoes/Fogoes de Piso,...,NaN,NaN,Voltagem,Bivolt,NaN,NaN,NaN,NaN,NaN,Sim
1,154520115,Ativo,Fogão 5 Bocas Atlas Acendimento Automático Mes...,MKP000418000123,7897180505370,NaN,0,Fogão 5 Bocas Atlas Acendimento Automático Mes...,<h2>Fogão 5 Bocas Atlas Mônaco Plus Titanium C...,Eletrodomesticos/Fogoes/Fogoes de Piso,...,https://suc.webcontinental.com.br/imagens_prod...,https://suc.webcontinental.com.br/imagens_prod...,Voltagem,Bivolt,NaN,NaN,NaN,NaN,NaN,Sim
2,317626037,Ativo,Fogão 5 Bocas Preto Com Mesa Inox Dako Magiste...,MKP000418000215,7897180598808,NaN,0,Fogão 5 Bocas Preto Com Mesa Inox Dako Magiste...,<h2>Fogão 5 Bocas Preto Com Mesa Inox Dako Mag...,Eletrodomesticos/Fogoes/Fogoes de Piso,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim
3,317626044,Ativo,Fogão 4 Bocas Preto Com Mesa Inox Dako Magiste...,MKP000418000216,7897180598792,NaN,0,Fogão 4 Bocas Preto Com Mesa Inox Dako Magiste...,<h2>Fogão 4 Bocas Preto Com Mesa Inox Dako Mag...,Eletrodomesticos/Fogoes/Fogoes de Piso,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim
4,318606111,Ativo,Fogão 5 Bocas Branco Com Mesa Inox Atlas Atena...,MKP000418000217,7897180510398,NaN,0,Fogão 5 Bocas Branco Com Mesa Inox Atlas Atena...,<h2>Fogão 5 Bocas Branco Com Mesa Inox Atlas A...,Eletrodomesticos/Fogoes/Fogoes de Piso,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim

In [35]:
# The .info() function will display the concise summary of an dataframe.
df_transport.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1842 entries, 0 to 1841
Data columns (total 45 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   AGRUPADOR                        1842 non-null   int64
 1   STATUS                           1842 non-null   object
 2   TÍTULO                           1842 non-null   object
 3   CÓDIGO FORNECEDOR / SKU INTERNO  1842 non-null   object
 4   EAN                              1507 non-null   object
 5   NBM                              961 non-null    float64
 6   ORIGEM                           1842 non-null   int64
 7   DESCRICAO                        1842 non-null   object
 8   DESCRIPTION                      1842 non-null   object
 9   CATEGORIA                        1842 non-null   object
 10  MARCA                            1836 non-null   object
 11  CÓDIGO INTERNO                   1842 non-null   int64
 12  MODELO                           1824 non-null   object
 13  PESO                             1842 non-null   float64
 14  PROFUNDIDADE                     1842 non-null   float64
 15  LARGURA                          1842 non-null   float64
 16  ALTURA                           1842 non-null   float64
 17  TEMPO DE GARANTIA                1839 non-null   float64
 18  TEXTO DE GARANTIA                1824 non-null   object
 19  VÍDEO                            0 non-null      float64
 20  CÁLCULO DE PREÇO                 1842 non-null   object
 21  CUSTO                            1842 non-null   float64
 22  MARKUP                           1842 non-null   int64
 23  PREÇO DE                         1842 non-null   float64
 24  PREÇO POR                        1842 non-null   float64
 25  QTD                              1842 non-null   int64
 26  PRAZO ADICIONAL                  1842 non-null   int64
 27  IMAGEM 1                         1838 non-null   object
 28  IMAGEM 2                         1770 non-null   object
 29  IMAGEM 3                         1640 non-null   object
 30  IMAGEM 4                         1401 non-null   object
 31  IMAGEM 5                         1131 non-null   object
 32  IMAGEM 6                         897 non-null    object
 33  IMAGEM 7                         614 non-null    object
 34  IMAGEM 8                         407 non-null    object
 35  IMAGEM 9                         268 non-null    object
 36  IMAGEM 10                        200 non-null    object
 37  NOME VARIAÇÃO 1                  595 non-null    object
 38  VALOR VARIAÇÃO 1                 595 non-null    object
 39  NOME VARIAÇÃO 2                  0 non-null      float64
 40  VALOR VARIAÇÃO 2                 0 non-null      float64
 41  NOME VARIAÇÃO 3                  0 non-null      float64
 42  VALOR VARIAÇÃO 3                 0 non-null      float64
 43  GÊNERO                           0 non-null      float64
 44  PERMITIR ANÚNCIOS AUTOMÁTICOS    1842 non-null   object
dtypes: float64(15), int64(6), object(24)
memory usage: 647.7+ KB

In [36]:
# Let's print out the first and last five rows of each column.
print(df_transport,5)

      AGRUPADOR STATUS                                             TÍTULO  \
0     154519990  Ativo  Fogão 4 Bocas Atlas Titanium Automático E Mesa...
1     154520115  Ativo  Fogão 5 Bocas Atlas Acendimento Automático Mes...
2     317626037  Ativo  Fogão 5 Bocas Preto Com Mesa Inox Dako Magiste...
3     317626044  Ativo  Fogão 4 Bocas Preto Com Mesa Inox Dako Magiste...
4     318606111  Ativo  Fogão 5 Bocas Branco Com Mesa Inox Atlas Atena...
...         ...    ...                                                ...
1837  319631392  Ativo  Fogão Itatiaia 5 Bocas Digital Itamaster Preto...
1838  319642172  Ativo  Freezer Horizontal Inverter Dupla Ação 543 Lit...
1839  319642185  Ativo  Geladeira Refrigerador 245 Litros Branca Roc31...
1840  319642189  Ativo  Freezer Horizontal Dupla Ação 468 Litros Tampa...
1841  319642196  Ativo  Freezer Horizontal Dupla Ação 325 Litros Tampa...

     CÓDIGO FORNECEDOR / SKU INTERNO            EAN  NBM  ORIGEM  \
0                    MKP000418000118  7897180505332  NaN       0
1                    MKP000418000123  7897180505370  NaN       0
2                    MKP000418000215  7897180598808  NaN       0
3                    MKP000418000216  7897180598792  NaN       0
4                    MKP000418000217  7897180510398  NaN       0
...                              ...            ...  ...     ...
1837                 MKP001721004212  7892946437841  NaN       0
1838                 MKP001910001472  7899908799849  NaN       0
1839                 MKP001910001502  7899081700786  NaN       0
1840                 MKP001910001503  7899081701240  NaN       0
1841                 MKP001910001504  7899081701226  NaN       0

                                              DESCRICAO  \
0     Fogão 4 Bocas Atlas Titanium Automático E Mesa...
1     Fogão 5 Bocas Atlas Acendimento Automático Mes...
2     Fogão 5 Bocas Preto Com Mesa Inox Dako Magiste...
3     Fogão 4 Bocas Preto Com Mesa Inox Dako Magiste...
4     Fogão 5 Bocas Branco Com Mesa Inox Atlas Atena...
...                                                 ...
1837  Fogão Itatiaia 5 Bocas Digital Itamaster Preto...
1838  Freezer Horizontal Inverter Dupla Ação 543 Lit...
1839  Geladeira Refrigerador 245 Litros Branca Roc31...
1840  Freezer Horizontal Dupla Ação 468 Litros Tampa...
1841  Freezer Horizontal Dupla Ação 325 Litros Tampa...

                                            DESCRIPTION  \
0     <h2>Fogão 4 Bocas Atlas Mônaco Plus Titanium C...
1     <h2>Fogão 5 Bocas Atlas Mônaco Plus Titanium C...
2     <h2>Fogão 5 Bocas Preto Com Mesa Inox Dako Mag...
3     <h2>Fogão 4 Bocas Preto Com Mesa Inox Dako Mag...
4     <h2>Fogão 5 Bocas Branco Com Mesa Inox Atlas A...
...                                                 ...
1837  <h2>Fogão Itatiaia 5 Bocas Digital Itamaster P...
1838  <h2>Freezer Horizontal Inverter Dupla Ação 543...
1839  <h2>Geladeira Refrigerador 245 Litros Branca R...
1840  <h2>Freezer Horizontal Dupla Ação 468 Litros T...
1841  <h2>Freezer Horizontal Dupla Ação 325 Litros T...

                                       CATEGORIA  ...  \
0         Eletrodomesticos/Fogoes/Fogoes de Piso  ...
1         Eletrodomesticos/Fogoes/Fogoes de Piso  ...
2         Eletrodomesticos/Fogoes/Fogoes de Piso  ...
3         Eletrodomesticos/Fogoes/Fogoes de Piso  ...
4         Eletrodomesticos/Fogoes/Fogoes de Piso  ...
...                                          ...  ...
1837      Eletrodomesticos/Fogoes/Fogoes de Piso  ...
1838                   Eletrodomesticos/Freezers  ...
1839  Eletrodomesticos/Refrigeradores-Geladeiras  ...
1840                   Eletrodomesticos/Freezers  ...
1841                   Eletrodomesticos/Freezers  ...

                                               IMAGEM 9  \
0                                                   NaN
1     https://suc.webcontinental.com.br/imagens_prod...
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
1837                                                NaN
1838                                                NaN
1839                                                NaN
1840                                                NaN
1841                                                NaN

                                              IMAGEM 10 NOME VARIAÇÃO 1  \
0                                                   NaN        Voltagem
1     https://suc.webcontinental.com.br/imagens_prod...        Voltagem
2                                                   NaN             NaN
3                                                   NaN             NaN
4                                                   NaN             NaN
...                                                 ...             ...
1837                                                NaN             NaN
1838                                                NaN             NaN
1839                                                NaN             NaN
1840                                                NaN             NaN
1841                                                NaN             NaN

      VALOR VARIAÇÃO 1  NOME VARIAÇÃO 2  VALOR VARIAÇÃO 2  NOME VARIAÇÃO 3  \
0               Bivolt              NaN               NaN              NaN
1               Bivolt              NaN               NaN              NaN
2                  NaN              NaN               NaN              NaN
3                  NaN              NaN               NaN              NaN
4                  NaN              NaN               NaN              NaN
...                ...              ...               ...              ...
1837               NaN              NaN               NaN              NaN
1838               NaN              NaN               NaN              NaN
1839               NaN              NaN               NaN              NaN
1840               NaN              NaN               NaN              NaN
1841               NaN              NaN               NaN              NaN

      VALOR VARIAÇÃO 3 GÊNERO  PERMITIR ANÚNCIOS AUTOMÁTICOS
0                  NaN    NaN                            Sim
1                  NaN    NaN                            Sim
2                  NaN    NaN                            Sim
3                  NaN    NaN                            Sim
4                  NaN    NaN                            Sim
...                ...    ...                            ...
1837               NaN    NaN                            Sim
1838               NaN    NaN                            Sim
1839               NaN    NaN                            Sim
1840               NaN    NaN                            Sim
1841               NaN    NaN                            Sim

[1842 rows x 45 columns] 5

In [37]:
# We can use .describe() to see some summary statistics for the numeric fields in our dataframe.
df_transport.describe()

,AGRUPADOR,NBM,ORIGEM,CÓDIGO INTERNO,PESO,PROFUNDIDADE,LARGURA,ALTURA,TEMPO DE GARANTIA,VÍDEO,...,MARKUP,PREÇO DE,PREÇO POR,QTD,PRAZO ADICIONAL,NOME VARIAÇÃO 2,VALOR VARIAÇÃO 2,NOME VARIAÇÃO 3,VALOR VARIAÇÃO 3,GÊNERO
count,1.842000e+03,9.610000e+02,1842.0,1.842000e+03,1842.00000,1842.000000,1842.000000,1842.000000,1839.000000,0.0,...,1842.0,1842.000000,1842.000000,1842.000000,1842.000000,0.0,0.0,0.0,0.0,0.0
mean,2.500053e+08,8.121325e+07,0.0,2.304227e+07,39.49490,60.472231,65.882872,81.987307,8.326808,NaN,...,1.0,2566.847291,2566.847291,136.546688,4.811075,NaN,NaN,NaN,NaN,NaN
std,6.652617e+07,6.000613e+06,0.0,1.373851e+08,70.26586,34.253180,37.988800,70.142648,5.025755,NaN,...,0.0,2824.870515,2824.870515,609.332124,3.987368,NaN,NaN,NaN,NaN,NaN
min,1.819730e+07,3.906905e+07,0.0,3.424000e+03,0.01000,0.400000,0.500000,0.340000,0.000000,NaN,...,1.0,75.010000,75.010000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN
25%,1.981584e+08,7.321190e+07,0.0,3.795000e+03,11.45000,48.800000,51.700000,42.275000,3.000000,NaN,...,1.0,799.900000,799.900000,8.000000,3.000000,NaN,NaN,NaN,NaN,NaN
50%,2.712542e+08,8.418100e+07,0.0,4.446000e+03,24.45000,60.000000,62.000000,70.000000,12.000000,NaN,...,1.0,1739.495000,1739.495000,20.000000,3.000000,NaN,NaN,NaN,NaN,NaN
75%,3.107490e+08,8.450209e+07,0.0,4.963000e+03,48.55000,71.500000,75.375000,98.000000,12.000000,NaN,...,1.0,3254.175000,3254.175000,90.000000,4.000000,NaN,NaN,NaN,NaN,NaN
max,3.196422e+08,9.401390e+07,0.0,1.871330e+09,666.99900,799.000000,738.000000,1804.000000,90.000000,NaN,...,1.0,25999.000000,25999.000000,13837.000000,35.000000,NaN,NaN,NaN,NaN,NaN

In [40]:
# The .groupby() function is used for spliting the data into groups based on some criteria.
grouped_data = df_transport.groupby(['AGRUPADOR','NBM','ORIGEM','CÓDIGO INTERNO','PESO','PROFUNDIDADE'])

 # Get the first entry for each month.
df_transport.groupby('AGRUPADOR').first()

,STATUS,TÍTULO,CÓDIGO FORNECEDOR / SKU INTERNO,EAN,NBM,ORIGEM,DESCRICAO,DESCRIPTION,CATEGORIA,MARCA,...,IMAGEM 9,IMAGEM 10,NOME VARIAÇÃO 1,VALOR VARIAÇÃO 1,NOME VARIAÇÃO 2,VALOR VARIAÇÃO 2,NOME VARIAÇÃO 3,VALOR VARIAÇÃO 3,GÊNERO,PERMITIR ANÚNCIOS AUTOMÁTICOS
AGRUPADOR,,,,,,,,,,,,,,,,,,,,,
18197295,Ativo,Coifa de Parede Gourmet Cadence Vidro Curvo 60...,MKP000172000852,7898615980960,NaN,0,Coifa de Parede Gourmet Cadence Vidro Curvo 60...,Coifa de Parede Gourmet Cadence Vidro Curvo 60...,Eletrodomesticos/Coifas,CADENCE,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,Sim
18198483,Ativo,Refrigerador Inverter Black Glass 425L Preto P...,MKP000192001639,7896067226643,NaN,0,Refrigerador Inverter Black Glass 425L Preto P...,Refrigerador Inverter Black Glass Frost Free 4...,Eletrodomesticos/Refrigeradores-Geladeiras,PANASONIC,...,https://suc.webcontinental.com.br/imagens_prod...,https://suc.webcontinental.com.br/imagens_prod...,None,None,NaN,NaN,NaN,NaN,NaN,Sim
20350080,Ativo,Fogão de Piso 5 Queimadores 2 Fornos Inox Bras...,MKP000192001796,7891129264717,39069049.0,0,Fogão de Piso 5 Queimadores 2 Fornos Inox Bras...,<h1>Fogão de Piso 5 Queimadores 2 Fornos Inox ...,Eletrodomesticos/Fogoes/Fogoes de Piso,BRASTEMP,...,https://suc.webcontinental.com.br/imagens_prod...,None,None,None,NaN,NaN,NaN,NaN,NaN,Sim
20895515,Ativo,Adega Piubella 100L 24 Garrafas Preta Venax 11...,MKP000192002101,7899552103795,NaN,0,Adega Piubella 100L 24 Garrafas Preta Venax 11...,<h2>Adega Piubella 100L 24 Garrafas Preta Vena...,Eletrodomesticos/Adegas e Champanheiras,VENAX,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,Sim
21613550,Ativo,Cooktop a Gás 4 Bocas Mega Chama Bivolt D&D Me...,MKP000613000005,0606529438227,73211100.0,0,Cooktop a Gás 4 Bocas Mega Chama Bivolt D&D Me...,<strong>Cooktop a Gás 4 Bocas Azul Mega Chama ...,Eletrodomesticos/Cooktops,D&D METAL,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319631392,Ativo,Fogão Itatiaia 5 Bocas Digital Itamaster Preto...,MKP001721004212,7892946437841,NaN,0,Fogão Itatiaia 5 Bocas Digital Itamaster Preto...,<h2>Fogão Itatiaia 5 Bocas Digital Itamaster P...,Eletrodomesticos/Fogoes/Fogoes de Piso,ITATIAIA,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,Sim
319642172,Ativo,Freezer Horizontal Inverter Dupla Ação 543 Lit...,MKP001910001472,7899908799849,NaN,0,Freezer Horizontal Inverter Dupla Ação 543 Lit...,<h2>Freezer Horizontal Inverter Dupla Ação 543...,Eletrodomesticos/Freezers,METALFRIO,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,Sim
319642185,Ativo,Geladeira Refrigerador 245 Litros Branca Roc31...,MKP001910001502,7899081700786,NaN,0,Geladeira Refrigerador 245 Litros Branca Roc31...,<h2>Geladeira Refrigerador 245 Litros Branca R...,Eletrodomesticos/Refrigeradores-Geladeiras,ESMALTEC,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,Sim
319642189,Ativo,Freezer Horizontal Dupla Ação 468 Litros Tampa...,MKP001910001503,7899081701240,NaN,0,Freezer Horizontal Dupla Ação 468 Litros Tampa...,<h2>Freezer Horizontal Dupla Ação 468 Litros T...,Eletrodomesticos/Freezers,ESMALTEC,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,Sim
319642196,Ativo,Freezer Horizontal Dupla Ação 325 Litros Tampa...,MKP001910001504,7899081701226,NaN,0,Freezer Horizontal Dupla Ação 325 Litros Tampa...,<h2>Freezer Horizontal Dupla Ação 325 Litros T...,Eletrodomesticos/Freezers,ESMALTEC,...,None,None,None,None,NaN,NaN,NaN,NaN,NaN,Sim

In [41]:
#Let's show the null values for all features in the DataFrame.
df_transport.isnull().sum()

AGRUPADOR                             0
STATUS                                0
TÍTULO                                0
CÓDIGO FORNECEDOR / SKU INTERNO       0
EAN                                 335
NBM                                 881
ORIGEM                                0
DESCRICAO                             0
DESCRIPTION                           0
CATEGORIA                             0
MARCA                                 6
CÓDIGO INTERNO                        0
MODELO                               18
PESO                                  0
PROFUNDIDADE                          0
LARGURA                               0
ALTURA                                0
TEMPO DE GARANTIA                     3
TEXTO DE GARANTIA                    18
VÍDEO                              1842
CÁLCULO DE PREÇO                      0
CUSTO                                 0
MARKUP                                0
PREÇO DE                              0
PREÇO POR                             0
QTD                                   0
PRAZO ADICIONAL                       0
IMAGEM 1                              4
IMAGEM 2                             72
IMAGEM 3                            202
IMAGEM 4                            441
IMAGEM 5                            711
IMAGEM 6                            945
IMAGEM 7                           1228
IMAGEM 8                           1435
IMAGEM 9                           1574
IMAGEM 10                          1642
NOME VARIAÇÃO 1                    1247
VALOR VARIAÇÃO 1                   1247
NOME VARIAÇÃO 2                    1842
VALOR VARIAÇÃO 2                   1842
NOME VARIAÇÃO 3                    1842
VALOR VARIAÇÃO 3                   1842
GÊNERO                             1842
PERMITIR ANÚNCIOS AUTOMÁTICOS         0
dtype: int64

In [44]:
print (df_transport['CATEGORIA'])
print (df_transport['CATEGORIA'].isnull())

0           Eletrodomesticos/Fogoes/Fogoes de Piso
1           Eletrodomesticos/Fogoes/Fogoes de Piso
2           Eletrodomesticos/Fogoes/Fogoes de Piso
3           Eletrodomesticos/Fogoes/Fogoes de Piso
4           Eletrodomesticos/Fogoes/Fogoes de Piso
                           ...
1837        Eletrodomesticos/Fogoes/Fogoes de Piso
1838                     Eletrodomesticos/Freezers
1839    Eletrodomesticos/Refrigeradores-Geladeiras
1840                     Eletrodomesticos/Freezers
1841                     Eletrodomesticos/Freezers
Name: CATEGORIA, Length: 1842, dtype: object
0       False
1       False
2       False
3       False
4       False
        ...
1837    False
1838    False
1839    False
1840    False
1841    False
Name: CATEGORIA, Length: 1842, dtype: bool

In [45]:
# In Python shape() is used in pandas to give the number of rows/columns.
# The number of rows is given by .shape[0]. The number of columns is given by .shape[1].
# Thus, shape() consists of an array having two arguments -- rows and columns
print ("Rows     : " ,df_transport.shape[0])
print ("Columns  : " ,df_transport.shape[1])
print ("\nFeatures : \n" ,df_transport.columns.tolist())
print ("\nUnique values :  \n",df_transport.nunique())
print ("\nMissing values :  ", df_transport.isnull().sum().values.sum())

Rows     :  1842
Columns  :  45

Features :
 ['AGRUPADOR', 'STATUS', 'TÍTULO', 'CÓDIGO FORNECEDOR / SKU INTERNO', 'EAN', 'NBM', 'ORIGEM', 'DESCRICAO', 'DESCRIPTION', 'CATEGORIA', 'MARCA', 'CÓDIGO INTERNO', 'MODELO', 'PESO', 'PROFUNDIDADE', 'LARGURA', 'ALTURA', 'TEMPO DE GARANTIA', 'TEXTO DE GARANTIA', 'VÍDEO', 'CÁLCULO DE PREÇO', 'CUSTO', 'MARKUP', 'PREÇO DE', 'PREÇO POR', 'QTD', 'PRAZO ADICIONAL', 'IMAGEM 1', 'IMAGEM 2', 'IMAGEM 3', 'IMAGEM 4', 'IMAGEM 5', 'IMAGEM 6', 'IMAGEM 7', 'IMAGEM 8', 'IMAGEM 9', 'IMAGEM 10', 'NOME VARIAÇÃO 1', 'VALOR VARIAÇÃO 1', 'NOME VARIAÇÃO 2', 'VALOR VARIAÇÃO 2', 'NOME VARIAÇÃO 3', 'VALOR VARIAÇÃO 3', 'GÊNERO', 'PERMITIR ANÚNCIOS AUTOMÁTICOS']

Unique values :
 AGRUPADOR                          1492
STATUS                                1
TÍTULO                             1416
CÓDIGO FORNECEDOR / SKU INTERNO    1492
EAN                                 946
NBM                                  30
ORIGEM                                1
DESCRICAO                          1421
DESCRIPTION                        1456
CATEGORIA                            22
MARCA                                93
CÓDIGO INTERNO                       95
MODELO                              106
PESO                                445
PROFUNDIDADE                        232
LARGURA                             287
ALTURA                              312
TEMPO DE GARANTIA                     9
TEXTO DE GARANTIA                    12
VÍDEO                                 0
CÁLCULO DE PREÇO                      2
CUSTO                               951
MARKUP                                1
PREÇO DE                            951
PREÇO POR                           951
QTD                                 297
PRAZO ADICIONAL                      18
IMAGEM 1                           1489
IMAGEM 2                           1428
IMAGEM 3                           1327
IMAGEM 4                           1123
IMAGEM 5                            897
IMAGEM 6                            714
IMAGEM 7                            498
IMAGEM 8                            325
IMAGEM 9                            211
IMAGEM 10                           157
NOME VARIAÇÃO 1                       1
VALOR VARIAÇÃO 1                      5
NOME VARIAÇÃO 2                       0
VALOR VARIAÇÃO 2                      0
NOME VARIAÇÃO 3                       0
VALOR VARIAÇÃO 3                      0
GÊNERO                                0
PERMITIR ANÚNCIOS AUTOMÁTICOS         1
dtype: int64

Missing values :   23061

In [46]:
# Output the last five rows in the dataset.
df_transport.tail()

,AGRUPADOR,STATUS,TÍTULO,CÓDIGO FORNECEDOR / SKU INTERNO,EAN,NBM,ORIGEM,DESCRICAO,DESCRIPTION,CATEGORIA,...,IMAGEM 9,IMAGEM 10,NOME VARIAÇÃO 1,VALOR VARIAÇÃO 1,NOME VARIAÇÃO 2,VALOR VARIAÇÃO 2,NOME VARIAÇÃO 3,VALOR VARIAÇÃO 3,GÊNERO,PERMITIR ANÚNCIOS AUTOMÁTICOS
1837,319631392,Ativo,Fogão Itatiaia 5 Bocas Digital Itamaster Preto...,MKP001721004212,7892946437841,NaN,0,Fogão Itatiaia 5 Bocas Digital Itamaster Preto...,<h2>Fogão Itatiaia 5 Bocas Digital Itamaster P...,Eletrodomesticos/Fogoes/Fogoes de Piso,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim
1838,319642172,Ativo,Freezer Horizontal Inverter Dupla Ação 543 Lit...,MKP001910001472,7899908799849,NaN,0,Freezer Horizontal Inverter Dupla Ação 543 Lit...,<h2>Freezer Horizontal Inverter Dupla Ação 543...,Eletrodomesticos/Freezers,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim
1839,319642185,Ativo,Geladeira Refrigerador 245 Litros Branca Roc31...,MKP001910001502,7899081700786,NaN,0,Geladeira Refrigerador 245 Litros Branca Roc31...,<h2>Geladeira Refrigerador 245 Litros Branca R...,Eletrodomesticos/Refrigeradores-Geladeiras,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim
1840,319642189,Ativo,Freezer Horizontal Dupla Ação 468 Litros Tampa...,MKP001910001503,7899081701240,NaN,0,Freezer Horizontal Dupla Ação 468 Litros Tampa...,<h2>Freezer Horizontal Dupla Ação 468 Litros T...,Eletrodomesticos/Freezers,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim
1841,319642196,Ativo,Freezer Horizontal Dupla Ação 325 Litros Tampa...,MKP001910001504,7899081701226,NaN,0,Freezer Horizontal Dupla Ação 325 Litros Tampa...,<h2>Freezer Horizontal Dupla Ação 325 Litros T...,Eletrodomesticos/Freezers,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sim

In [47]:
# The isnull() method is used to check and manage NULL values in a data frame.
# TODO 1a
df_transport.isnull().sum()

AGRUPADOR                             0
STATUS                                0
TÍTULO                                0
CÓDIGO FORNECEDOR / SKU INTERNO       0
EAN                                 335
NBM                                 881
ORIGEM                                0
DESCRICAO                             0
DESCRIPTION                           0
CATEGORIA                             0
MARCA                                 6
CÓDIGO INTERNO                        0
MODELO                               18
PESO                                  0
PROFUNDIDADE                          0
LARGURA                               0
ALTURA                                0
TEMPO DE GARANTIA                     3
TEXTO DE GARANTIA                    18
VÍDEO                              1842
CÁLCULO DE PREÇO                      0
CUSTO                                 0
MARKUP                                0
PREÇO DE                              0
PREÇO POR                             0
QTD                                   0
PRAZO ADICIONAL                       0
IMAGEM 1                              4
IMAGEM 2                             72
IMAGEM 3                            202
IMAGEM 4                            441
IMAGEM 5                            711
IMAGEM 6                            945
IMAGEM 7                           1228
IMAGEM 8                           1435
IMAGEM 9                           1574
IMAGEM 10                          1642
NOME VARIAÇÃO 1                    1247
VALOR VARIAÇÃO 1                   1247
NOME VARIAÇÃO 2                    1842
VALOR VARIAÇÃO 2                   1842
NOME VARIAÇÃO 3                    1842
VALOR VARIAÇÃO 3                   1842
GÊNERO                             1842
PERMITIR ANÚNCIOS AUTOMÁTICOS         0
dtype: int64

In [49]:
# Date is now converted and will display the concise summary of an dataframe.
# TODO 2b
df_transport.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1842 entries, 0 to 1841
Data columns (total 45 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   AGRUPADOR                        1842 non-null   int64
 1   STATUS                           1842 non-null   object
 2   TÍTULO                           1842 non-null   object
 3   CÓDIGO FORNECEDOR / SKU INTERNO  1842 non-null   object
 4   EAN                              1507 non-null   object
 5   NBM                              961 non-null    float64
 6   ORIGEM                           1842 non-null   int64
 7   DESCRICAO                        1842 non-null   object
 8   DESCRIPTION                      1842 non-null   object
 9   CATEGORIA                        1842 non-null   object
 10  MARCA                            1836 non-null   object
 11  CÓDIGO INTERNO                   1842 non-null   int64
 12  MODELO                           1824 non-null   object
 13  PESO                             1842 non-null   float64
 14  PROFUNDIDADE                     1842 non-null   float64
 15  LARGURA                          1842 non-null   float64
 16  ALTURA                           1842 non-null   float64
 17  TEMPO DE GARANTIA                1839 non-null   float64
 18  TEXTO DE GARANTIA                1824 non-null   object
 19  VÍDEO                            0 non-null      float64
 20  CÁLCULO DE PREÇO                 1842 non-null   object
 21  CUSTO                            1842 non-null   float64
 22  MARKUP                           1842 non-null   int64
 23  PREÇO DE                         1842 non-null   float64
 24  PREÇO POR                        1842 non-null   float64
 25  QTD                              1842 non-null   int64
 26  PRAZO ADICIONAL                  1842 non-null   int64
 27  IMAGEM 1                         1838 non-null   object
 28  IMAGEM 2                         1770 non-null   object
 29  IMAGEM 3                         1640 non-null   object
 30  IMAGEM 4                         1401 non-null   object
 31  IMAGEM 5                         1131 non-null   object
 32  IMAGEM 6                         897 non-null    object
 33  IMAGEM 7                         614 non-null    object
 34  IMAGEM 8                         407 non-null    object
 35  IMAGEM 9                         268 non-null    object
 36  IMAGEM 10                        200 non-null    object
 37  NOME VARIAÇÃO 1                  595 non-null    object
 38  VALOR VARIAÇÃO 1                 595 non-null    object
 39  NOME VARIAÇÃO 2                  0 non-null      float64
 40  VALOR VARIAÇÃO 2                 0 non-null      float64
 41  NOME VARIAÇÃO 3                  0 non-null      float64
 42  VALOR VARIAÇÃO 3                 0 non-null      float64
 43  GÊNERO                           0 non-null      float64
 44  PERMITIR ANÚNCIOS AUTOMÁTICOS    1842 non-null   object
dtypes: float64(15), int64(6), object(24)
memory usage: 647.7+ KB